apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: python-app-container
          image: 223733897421.dkr.ecr.ap-south-1.amazonaws.com/python-ecr-repo:latest
          imagePullPolicy: Always  
          ports:
            - containerPort: 80
